/* --(c) Copyright 2013 Grameen Foundation USA. All rights reserved */
	.unsavedChangesDialog{display:none;}
    #simplemodal-overlay {background-color:#000;}
    #simplemodal-container {background-color:white; border:3px solid #444; padding:12px;}
    .butn{float:right;cursor:pointer;}
    table#navigationBar td{font-weight:bold}
    table#navigationBar td.ns{background:white;cursor:pointer;font-weight:normal}
    table#navigationBar td.ns:hover{opacity:0.75;font-weight:bold}